##
# \file Dockerfile-centos
# \brief Dockerfile to create centos overware ovbuilder
# \author Jeremy HERGAULT (reneca)
# \version 1.0
# \date 2019-02-17
#
# This file is part of OVBuilder, which is builder for overware programs.
# Copyright (C) 2019  HERGAULT Jeremy, Alexandre, Thierry ( reneca )
#
# OVBuilder is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# OVBuilder is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OVCloud. If not, see <http://www.gnu.org/licenses/>.
##

FROM centos:7
MAINTAINER HERGAULT Jeremy <reneca@overware.fr>
LABEL Description="OVBuilder for overware programs" Vendor="overware" Version="1.0"

ENV DOCKERCOMPIL=true \
    PATH="${PATH}:/usr/local/bin"

ARG OPENSSL_PACKAGE=openssl-1.1.1b
ARG ZLIB_PACKAGE=1.2.8

COPY scripts/select-product.sh scripts/build-product /usr/local/bin/

RUN yum -y install epel-release centos-release-scl && yum -y install \
      procps \
      wget \
      curl \
      perl \
      kernel-devel \
      vim \
      git \
      make \
      gcc \
      gcc-c++ \
      elfutils \
      openssl \
 && yum -y clean all \
 && mkdir -p /sources/objs /opt \
 && curl https://www.openssl.org/source/${OPENSSL_PACKAGE}.tar.gz -o /tmp/openssl.tar.gz \
 && tar zxf /tmp/openssl.tar.gz -C /sources \
 && cd /sources/${OPENSSL_PACKAGE} \
 && ./config --prefix=/sources shared threads no-ssl3 \
 && make \
 && make install \
 && cd /tmp \
 && curl -LO https://github.com/RJVB/zlib-cloudflare/archive/v${ZLIB_PACKAGE}.tar.gz \
 && tar zxf v${ZLIB_PACKAGE}.tar.gz -C /sources \
 && cd /sources/zlib-cloudflare-${ZLIB_PACKAGE} \
 && ./configure --prefix=/sources --shared \
 && make \
 && make install \
 && rm -rf /sources/lib/libz*.a \
 && cp *.lo /sources/objs/ \
 && cd /sources/objs \
 && for lib in $(ls -d /sources/lib/*.a); do ar -x $lib; done \
 && rm -rf /tmp/* /var/cache/yum \
 && chmod +x /usr/local/bin/build-product

WORKDIR /opt

VOLUME /opt/

ENTRYPOINT ["/usr/local/bin/build-product"]


# End of Dockerfile
