##
# \file Dockerfile-alpine
# \brief Dockerfile to create alpine overware ovbuilder
# \author Jeremy HERGAULT (reneca)
# \version 1.0
# \date 2020-03-26
#
# This file is part of OVBuilder, which is builder for overware programs.
# Copyright (C) 2020  HERGAULT Jeremy, Alexandre, Thierry ( reneca )
#
# OVBuilder is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# OVBuilder is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OVCloud. If not, see <http://www.gnu.org/licenses/>.
##

FROM alpine
MAINTAINER HERGAULT Jeremy <reneca@overware.fr>
LABEL Description="OVBuilder for overware programs" Vendor="overware" Version="1.0"

ENV DOCKERCOMPIL=true \
    PATH="${PATH}:/usr/local/bin"

ARG OPENSSL_PACKAGE=openssl-1.1.1e
ARG ZLIB_PACKAGE=1.2.8

COPY scripts/select-product.sh scripts/make-product /usr/local/bin/

RUN apk add \
      bash \
      linux-headers \
      procps \
      wget \
      curl \
      perl \
      vim \
      git \
      make \
      gcc \
      g++ \
      musl-dev \
      libexecinfo-dev \
      elfutils \
      gtest-dev \
 && apk add --no-cache -X http://dl-cdn.alpinelinux.org/alpine/edge/testing \
      lcov \
 && mkdir -p /sources/objs /opt \
 && curl https://www.openssl.org/source/${OPENSSL_PACKAGE}.tar.gz -o /tmp/openssl.tar.gz \
 && tar zxf /tmp/openssl.tar.gz -C /sources \
 && cd /sources/${OPENSSL_PACKAGE} \
 && ./config --prefix=/sources shared threads no-comp no-idea no-dtls no-ssl3 no-weak-ssl-ciphers \
 && make \
 && make install \
 && cd /tmp \
 && curl -LO https://github.com/RJVB/zlib-cloudflare/archive/v${ZLIB_PACKAGE}.tar.gz \
 && tar zxf v${ZLIB_PACKAGE}.tar.gz -C /sources \
 && cd /sources/zlib-cloudflare-${ZLIB_PACKAGE} \
 && ./configure --prefix=/sources --shared \
 && make \
 && make install \
 && rm -rf /sources/lib/libz*.a \
 && cp *.lo /sources/objs/ \
 && cd /sources/objs \
 && for lib in $(ls -d /sources/lib/*.a); do ar -x $lib; done \
 && chmod 755 -R /sources/bin \
 && for header in $(ls /sources/include); do ln -snf /sources/include/$header /usr/include/$header; done \
 && for lib in $(ls /sources/lib); do ln -snf /sources/lib/$lib /usr/lib/$lib; done \
 && for bin in $(ls /sources/bin); do ln -snf /sources/bin/$bin /usr/bin/$bin; done \
 && rm -rf /tmp/* \
 && chmod +x /usr/local/bin/make-product

WORKDIR /opt

VOLUME /opt/

ENTRYPOINT ["/usr/local/bin/make-product"]


# End of Dockerfile
