#!/bin/bash
# \file build-rfc
# \brief Script to generate all rfcs associate to a program
# \author Jeremy HERGAULT (reneca)
# \version 1.0
# \date 2019-02-17
#
# This file is part of OVBuilder, which is builder for overware programs.
# Copyright (C) 2019  HERGAULT Jeremy, Alexandre, Thierry ( reneca )
#
# OVBuilder is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# OVBuilder is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OVCloud. If not, see <http://www.gnu.org/licenses/>.
##

# Select product directory
source /usr/local/bin/select-product.sh

if [ -d rfc/ ]; then
  for rfcfile in $(ls rfc/*.md | sed 's/\.md$//g'); do
    kramdown-rfc2629 $rfcfile.md > $rfcfile.xml
    if [ -z "$@" ]; then
      xml2rfc $rfcfile.xml --text --html --pdf
    else
      xml2rfc $rfcfile.xml $@
    fi
  done
fi

echo

# End of file
