#!/bin/bash
# \file build-cppanalysis
# \brief Script to do a cppcheck analysis and put the result to cpp.analysis
# \author Jeremy HERGAULT (reneca)
# \version 1.0
# \date 2019-02-17
#
# This file is part of OVBuilder, which is builder for overware programs.
# Copyright (C) 2019  HERGAULT Jeremy, Alexandre, Thierry ( reneca )
#
# OVBuilder is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# OVBuilder is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OVCloud. If not, see <http://www.gnu.org/licenses/>.
##

# Select product directory
source /usr/local/bin/select-product.sh

rm -rf cpp.analysis

cppcheck -j $PARALLEL -DLINUX -DLINUX_$(grep '^ID=' /etc/os-release | sed 's/^ID=//g' | tr -d '"' 2> /dev/null | tr [:lower:] [:upper:]) -DOBFUSCATEMEM --enable=all . 2> /tmp/analysis.txt
grep -v "(style) Class '[a-zA-Z<>,]*' has a constructor with [0-9] argument that is not explicit\.$" /tmp/analysis.txt > cpp.analysis


# End of script
